### ISSUE TITLE
Any development news ???

### ISSUE THREAD

**Issue by delfuria** [mitchdenny/palmer#20]
Hi, is there any development news about this project ??
The last release is older and no release are available.
Is this project still alive ??
Thanks

**Comment by CADbloke** [comment]
Apparently ot but have you seen https://github.com/michael-wolfenden/Polly ?

**Comment by mitchdenny** [comment]
I totally lost track of this :) I'm actually just updating the code to .NET Standard 2.0 for the few folks that might still be using it but Polly does look like a better option.

**Comment by delfuria** [comment]
Thanks a lot !!!
